version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORK_DIR=$WORK_DIR
    environment:
      - NODE_ENV=$NODE_ENV
    volumes:
      - type: bind
        source: ./
        target: $WORK_DIR
    command: sh -c 'cd web_ui && yarn start'
    ports:
      - target: 3000    # container
        published: 8000 # host
    stdin_open: true # -i
    tty: true # -t
