version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORK_DIR=$WORK_DIR
    environment:
      - NODE_ENV=$NODE_ENV
    volumes:
      - type: bind
        source: ./
        target: $WORK_DIR
    # command: sh -c 'cd frontend && yarn start'
    ports:
      - target: 8000
        published: 3000
    stdin_open: true # -i
    tty: true # -t
